name: Clean up GHCR

on:
  workflow_dispatch:

  schedule:
    - cron: '0 0 * * *'

permissions:
  packages: write

jobs:
  cleanup-ghcr:
    name: Clean up old GHCR images
    runs-on: ubuntu-latest

    steps:
      - name: Delete old alpha images
        uses: snok/container-retention-policy@d3bdcf5ce9b05f685154e4a16c39233b245e3d53   # v3.1.0
        with:
          account: Tiagura
          token: ${{ github.token }}
          image-names: "gotigram"
          image-tags: "alpha-*"
          cut-off: 2w
          keep-n-most-recent: 10